# Generated by Django 5.1.1 on 2024-09-22 09:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gamepad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('vendor_id', models.CharField(max_length=10)),
                ('product_id', models.CharField(max_length=10)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('led_red', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)])),
                ('led_green', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)])),
                ('led_blue', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)])),
                ('led_brightness', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='GamepadUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('Dpad_up', models.IntegerField(default=0)),
                ('Dpad_down', models.IntegerField(default=0)),
                ('Dpad_left', models.IntegerField(default=0)),
                ('Dpad_right', models.IntegerField(default=0)),
                ('cross_presses', models.IntegerField(default=0)),
                ('circle_presses', models.IntegerField(default=0)),
                ('square_presses', models.IntegerField(default=0)),
                ('triangle_presses', models.IntegerField(default=0)),
                ('l1_presses', models.IntegerField(default=0)),
                ('r1_presses', models.IntegerField(default=0)),
                ('l2_presses', models.IntegerField(default=0)),
                ('r2_presses', models.IntegerField(default=0)),
                ('l3_presses', models.IntegerField(default=0)),
                ('r3_presses', models.IntegerField(default=0)),
                ('share_presses', models.IntegerField(default=0)),
                ('options_presses', models.IntegerField(default=0)),
                ('ps_presses', models.IntegerField(default=0)),
                ('touchpad_presses', models.IntegerField(default=0)),
                ('left_stick_usage', models.FloatField(default=0)),
                ('right_stick_usage', models.FloatField(default=0)),
                ('gamepad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controller.gamepad')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_playtime', models.DurationField(default=0)),
                ('total_buttons_pressed', models.IntegerField(default=0)),
                ('right_stick_usage', models.FloatField(default=0)),
                ('left_stick_usage', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='gamepad',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamepads', to='controller.profile'),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('path', models.CharField(max_length=500)),
                ('last_played', models.DateTimeField(blank=True, null=True)),
                ('total_playtime', models.DurationField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='controller.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='screenshots/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='controller.profile')),
            ],
        ),
    ]
